# Generated by Django 4.1.5 on 2023-01-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="pub_date",
        ),
        migrations.RemoveField(
            model_name="question",
            name="question_text",
        ),
    ]
